version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8081:8081
      - 9229:9229
    environment:
      - NODE_ENV=development
    networks:
      - default
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: npm start

  masterdb:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: edsdk_emps_main
    networks:
      - default

networks:
  default:
