version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8081:8081
      - 9229:9229
    environment:
      - NODE_ENV=development
    networks:
      - default
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    entrypoint: yarn start

networks:
  default:
