name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test BE
        run: |
          cd Backend
          docker build -t my-node-app:latest .
          docker run -d my-node-app:latest 

      - name: Push image BE to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./Backend 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ github.sha }}
      
      - name: Build and test AI
        run: |
          cd ..
          cd AI 
          docker build -t my-fast-app:latest .
          docker run -d my-fast-app:latest  

      - name: Push image AI to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./AI 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-fast-app:${{ github.sha }}

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ github.sha }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-fast-app:${{ github.sha }}

            docker stop my-node-app
            docker rm my-node-app
            docker stop my-fast-app
            docker rm my-fast-app

            sudo docker run -d -p 6996:6996 --name my-node-app ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ github.sha }}
            sudo docker run -d -p 8000:8000 --name my-fast-app ${{ secrets.DOCKERHUB_USERNAME }}/my-fast-app:${{ github.sha }}
