name: Docker CI/CD Pipeline

# Xác định sự kiện trigger cho pipeline, trong trường hợp này là merge vào nhánh develop
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed

# Định nghĩa các jobs cần thực hiện 
jobs:
   # Job 1: build và test
   # Job thực thi trên máy ảo ubuntu
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Sử dụng action "checkout" để sao copy code từ repository vào máy ảo Ubuntu
        uses: actions/checkout@v2

      - name: Login to Docker Hub
          # Sử dụng action "docker/login-action" để đăng nhập vào Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        # Build và test image được build ra bằng Docker 
        run: |
          cd Backend
          docker build -t my-node-app:latest .
          docker run -d my-node-app:latest 

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        # Sử dụng action "docker/build-push-action" để đẩy image lên Docker Hub
        with:
          context: ./Backend 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ github.sha }}

 # Job 2: Deploy
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
       # Sử dụng action "appleboy/ssh-action" để triển khai image lên server thông qua SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull image mà được push lên DockerHub bên trên
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ github.sha }}

            # Dừng và gỡ bỏ container hiện tại (nếu có)
            docker stop my-node-app
            docker rm my-node-app

            # Chạy container mới với image đã pull về bên trên
            sudo docker run -d -p 6996:6996 --name my-node-app ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ github.sha }}

